# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CD - Nathan

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "npm"
  
      - run: npm run build
      - run: echo "pushing to ECR ..."
      - run: echo "this is now deployed to Staging"
      - run: echo "running playwright tests..."
      - run: npm run test